security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api/
            stateless: true
            jwt: ~
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AdminAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            remember_me:
                secret: "%kernel.secret%"
                lifetime: 604800
                path: /
                always_remember_me: true

    role_hierarchy:
        ROLE_RESPONSABLE: [ROLE_BIBLIOTHECAIRE, ROLE_MEMBRE, ROLE_USER]
        ROLE_BIBLIOTHECAIRE: [ROLE_MEMBRE, ROLE_USER]
        ROLE_MEMBRE: [ROLE_USER]

    access_control:
        - { path: ^/admin, roles: ROLE_RESPONSABLE }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/books, roles: PUBLIC_ACCESS }
        - { path: ^/api/authors, roles: PUBLIC_ACCESS }
        - { path: ^/api/categories, roles: PUBLIC_ACCESS }
        - { path: ^/api/admin, roles: ROLE_RESPONSABLE }
        - { path: ^/api/librarian, roles: ROLE_BIBLIOTHECAIRE }
        - { path: ^/api/user/me, roles: ROLE_USER }
        - { path: ^/api/me, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
